### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by bertt** [Geodan/plv8_libloader#3]
getting error after running psql -U postgres -f d3.sql:

```
cat: ./libraries/delaunator.js: No such file or directory
cat: ./libraries/geotiff.js: No such file or directory
```

**Comment by tomvantilburg** [comment]
I forgot to add `npm run build` to the instructions. Can you try?

**Comment by bertt** [comment]
program rollup is missing now... need to be added to npm packages?

**Comment by bertt** [comment]
./libraries/geotiff.js still missing after running  npm run build (delaunator.js is there now)

**Comment by bertt** [comment]
another error:
```
psql:d3.sql:48: ERROR:  language "plv8" does not exist
```

**Comment by tomvantilburg** [comment]
Removed geotiff per acae495836d0a80a610bdabb4bbae271bad3113e

**Comment by tomvantilburg** [comment]
Added plv8 as prerequisite per ec8cb9c23da77bc169414509a2f4747d7ff60621

**Comment by tomvantilburg** [comment]
Added rollup to dependencies per 40a5c5b4e7c0fd3d0b839a1c8e616ed694d1a7e0

**Comment by tomvantilburg** [comment]
Package should be working now, I didn't test rollup as a local dependencie though, in the past there were some issues with a non-global install of rollup.
